### ISSUE TITLE
1.0.0 Release Checklist

### ISSUE THREAD

**Issue by petr-muller** [petr-muller/pyff#19]
- [ ] `pyff-git uri old-revision new-revision`: Given a git repository and two version references, compare them
- [ ] `pyff.api`
- [ ] GitHub PR commenter
- [ ] Containerized GitHub PR commenter
- [ ] Containerized GitHub PR commenter running on OpenShift over pyff repo
- [ ] Proper README.md
- [ ] CONTRIBUTORS.md
- [ ] Issues populated with few ideas
